//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_CORS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILE
    {
        public Nullable<long> age { get; set; }
        public string id { get; set; }
        public string imageUrl { get; set; }
        public string name { get; set; }
        public string snippet { get; set; }
        public Nullable<long> sorted { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string detail { get; set; }
    }
}
