//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_CORS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string descriptions { get; set; }
        public Nullable<bool> is_show { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
